DELETE FROM Guests WHERE GuestId >0;
ALTER TABLE `timvasne_wedding`.`Guests` AUTO_INCREMENT = 1000 ;
DELETE FROM RSVP WHERE RsvpId > 0;
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Pam','Bean',1,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Brad','Bean',2,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Marilyn','Bean',2,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Robert','Wood',3,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Jennifer','Wood',3,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Dean','West',4,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Dan','Peck',5,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Robin','Peck',5,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Joe','Jeffers',6,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Marilyn','Jeffers',6,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Richard','Disney',7,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Alicia','Disney',7,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Matt','Burke',8,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Danielle','Burke',8,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Adam','Bourque',9,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Vica','Bourque',9,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Andrew','Fortenberry',10,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Ashley','Fortenberry',10,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Lowell','Yost',11,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Jerry','Yost',11,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Mike','Reed',12,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Lisa','Reed',12,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Debra','Vasnelis',13,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Patrick','Vasnelis',14,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Tammy','Dingler',14,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Michael','Essex',15,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Susan','Bower',15,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('George','Vasnelis',16,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Diana','Vasnelis',16,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Sam','Hall',17,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Nancy','Hall',17,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Bill','Weldon',18,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Laurie','Weldon',18,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Janice','Essex',19,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Steve','Hess',19,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Ryan','Vasnelis',20,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Dana','Stone',20,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Steve','Mena',21,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Lauren','Vasnelis',21,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Brian','Weldon',22,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Lauren','Jewski',22,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Andrew','Weldon',23,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Kristen','Weldon',23,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Daniel','Weldon',24,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Shannon','Slowey',24,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Katie','Byorick',25,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Becca','Byorick',26,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Meghan','Byorick',27,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Emily','Byorick',28,1,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Kim','Wiggins',29,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Mr','Banks ',30,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Lynn','Banks',30,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Patti','Linehan',31,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Greg','Follensbee',32,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Marsha','Follensbee',32,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Valerie','White',33,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Kris','Lay',34,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Bill','Blalock',35,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Cheryl','Blalock',35,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Nick','Kateras',36,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Alice','Kateras',36,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('George','Henshaw',37,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Kathy','Henshaw',37,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Barbie','Edge',38,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Leanne','Webber ',39,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('John','Casey',40,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Jo','Casey',40,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('John','Kalinich',41,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Madeline','Kalinich',41,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Donna','Degrau',42,4,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Shannon','Stowers',43,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Sarah','Stowers',43,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Michael','Whealen',44,2,1);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Mary','Hsu',45,2,1);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Christina','Lendemann',46,2,1);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Ben','Dessing',47,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Keri','Dessing',47,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Nick','Perez',48,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Ashley','Perez',48,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Brandon','Burris ',49,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Audrey','Burris',49,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Hawkeye','Wayne',50,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Beth','Wayne',50,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Kimberly','Straub',51,2,1);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Matthew','Shaefer',52,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Cammie','Shaefer',52,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Jace','Crooke',53,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Eva','Crooke',53,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Adam','Yeager',54,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Natasha','Yeager',54,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('John','Sissoyev ',55,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Stacy','Sissoyev ',55,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Terrie','Uiterwyk',56,2,1);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Ryan','Jaso',57,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Jennifer','Jaso',57,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Greg','VanHorn',58,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Christine','VanHorn',58,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Christian','VanHorn',59,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Kandace','Bisignano',59,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Ryan','VanHorn',60,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Jessica','VanHorn',60,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Alexandra','VanHorn',61,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Anthony','Ercolino',62,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Kimberly','Ercolino',62,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Dan','DeOliveira',63,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Jessica','Francesca',63,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Brian','Dietlein',64,2,1);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Joe','Lanza',65,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Lauren','Lanza',65,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Michael','Coad',66,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Lianne','Coad',66,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Jacob','Coad',67,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Liz','Coad',67,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Skip','Warmack',68,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Jessica','Warmack',68,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('David','Lubinsky',69,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Rachel','Lubinsky',69,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Neil','Scott',70,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Gail','Coad',70,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Rob','Thomas',71,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Lisa','Verhelle',71,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Josh','Wynne',72,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Michelle','Wynne',72,2,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Lisa','Dichtel',73,2,1);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Patrick','Knight ',74,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Katie','Knight ',74,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Fredrick','Mamlqvist ',75,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Ana','Mamlqvist ',75,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Robin','Hurley',76,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Plus','One',76,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Michael','Kehoe ',77,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Paula','Kehoe ',77,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('James','Fitch',78,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Nancy','Fitch',78,3,NULL);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Colby','Dennis',79,1,1);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Test','One',999,1,1);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Test','Two',999,1,0);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Test','Three',999,1,0);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Test','Four',999,1,0);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Test','Five',999,1,0);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne) VALUES ('Test','Six',999,1,0);
INSERT INTO Guests (FirstName, LastName, GroupId, Guest_CatId, PlusOne, PlusFamily) VALUES ('Test','Family',9999,1,1,1);
UPDATE Guests SET PlusOne=0 WHERE PlusOne is NULL;
UPDATE Guests SET PlusFamily=0 WHERE PlusFamily is NULL;
